# Generated by Django 4.1.7 on 2023-03-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbapp', '0002_devices_delete_my_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devices',
            name='power',
            field=models.IntegerField(),
        ),
    ]
